[package]
name = "algorithmplus"
version = "0.1.4"
authors = ["Satvik Shukla <satvikshukla9@gmail.com>"]
license = "MIT"
description = "Library of commonly used algorithms."
repository = "https://github.com/satvikshukla/algorithmplus"
readme = "README.md"
edition = "2018"

[dependencies]
